### PR TITLE
Create mongo seed db script 

### PR DESCRIPTION
**Pull request by federicorex**
I've struggled a bit with import/export management and database connections, but it seems working now. I've used a local connection for mongoDB (not Atlas).

### CODE REVIEW

**Review by hinchley2018 — COMMENTED** [review]
overall looks good, can you install mongodb as a dependency in package.json?
And add a script `"seed-db": "node db.js"` to the package.json so the seed script is easy to use

**Review by hinchley2018 — CHANGES_REQUESTED** [review]
overall looks good, can you install mongodb as a dependency in package.json?
And add a script `"seed-db": "node db.js"` to the package.json so the seed script is easy to use

After that i think this can be merged

**Comment by federicorex** [comment]
Ok the changes have been done, can you see them?

**Comment by federicorex** [comment]
There are few conflicts but I've never resolved them on GitHub so I prefer to not touch them just to not create problems on main.

**Review by hinchley2018 — APPROVED** [review]

**Pull request merged**
